### ISSUE TITLE
Link to the dev.to article in the readme

### ISSUE THREAD

**Issue by triptych** [Vinayak-k160/Gridsome-FaunaDB-Todo#3]
It would be very helpful if you linked to the dev.to article in your readme https://dev.to/vinayakk160/gridsome-faunadb-todo-app-24kb

**Comment by Vinayak-k160** [comment]
https://github.com/Vinayak-k160/Gridsome-FaunaDB-Todo/commit/a0ca6d97634916a84f818bdde8e43e20d0e20aca
